# Generated by Django 5.1.1 on 2024-10-03 07:42

from django.db import migrations

def add_initial_categories(apps, schema_editor):
    Movie = apps.get_model('tables', 'Movie')
    Movie.objects.create(
        title='Man: The Movie',
        releaseDate='2023-03-23',
        year=2023,
        director='Grant Wisler',
        genre='Drama'
    )

class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(add_initial_categories),
    ]
