# Generated by Django 4.2 on 2024-10-27 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0002_alter_watchlist_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='username',
            new_name='user_id',
        ),
    ]
