# Generated by Django 4.2 on 2024-10-15 22:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0003_remove_movie_releasedate_movie_poster_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='watchlist',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
