# Generated by Django 4.2 on 2024-10-15 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0004_alter_watchlist_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='watchlist',
            old_name='movie_id',
            new_name='movie',
        ),
        migrations.AddField(
            model_name='watchlist',
            name='watchlist_name',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='status',
            field=models.CharField(default='Not Watched', max_length=20),
        ),
    ]
