# Generated by Django 4.2 on 2024-10-23 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tables', '0007_rename_movie_id_watchlist_movie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='movie',
            name='poster',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='watchlist',
            name='watchlist_name',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
